export const LIST_CITIES = [
    { name: 'London' },
    { name: 'Alaska' },
    { name: 'Chicago' },
    { name: 'Arizonia' },
    { name: 'California' },
    { name: 'Arizonia' },
    { name: 'London' },
    { name: 'Milan' },
    { name: 'Berlin' },
    { name: 'Paris' },
    { name: 'Vienna' },
    { name: 'Amsterdam' },
    { name: 'New york' },
    { name: 'Glasgow' },
    { name: 'Dublin' },
    { name: 'San Diego' },
    { name: 'Bangkok' },
    { name: 'Tokyo' },
    { name: 'Beijing' },
    { name: 'Pune' },
    { name: 'Zurich' },
    { name: 'Bern' },
    { name: 'Vernier' },
    { name: 'Uster' },
    { name: 'Sion' },
    { name: 'Chur' },
    { name: 'Lucerne' },
    { name: 'Nagpur' }
  ];
